Magickbase/nervos-official-website

.eslintrc.cjs, next-i18next.config.js, next.config.mjs, public/locales/en/home.json, src/components/Footer/index.module.scss, src/components/Header/index.module.scss, src/components/Header/index.tsx, src/components/Page/index.tsx, src/hooks/index.ts, src/pages/home/SlideFooter/index.module.scss, src/pages/home/SlideFooter/index.tsx, src/pages/home/index.module.scss, src/pages/home/index.page.tsx, src/styles/variables.module.scss, tsconfig.json
Based on `@media (max-width: $mobileBreakPoint)` 和 `useIsMobile` to do mobile adaptation.
Ref: #9
=> feat: implement home page for mobile

package.json, src/pages/home/SlideFooter/index.tsx, src/server/api/routers/ckb.ts, src/services/ExplorerService/index.ts, src/services/ExplorerService/types.ts, src/utils/index.ts, src/utils/number.ts, tsconfig.json, yarn.lock
feat: implement api getLiveMetrics
Ref: #8
=> feat: implement api getLiveMetrics

src/pages/blogs/index.module.scss
=> feat: optimize banner of blogs for wide screen

src/components/ConwayGameOfLife/index.tsx, src/components/ConwayGameOfLife/useGameKeybindings.ts, src/components/ConwayGameOfLife/utils.ts, src/components/Footer/components/FooterMedia/index.tsx, src/components/Header/index.tsx, src/pages/home/Card/index.tsx, src/pages/home/SlideFooter/index.tsx, src/pages/home/index.page.tsx
feat: optimize the mouse interaction logic of the Conway Game of Life
Ref: #26
=> feat: optimize the mouse interaction logic of the Conway Game of Life

src/components/Footer/components/FooterLinkGroup/index.module.scss, src/components/Footer/components/FooterMedia/index.module.scss, src/components/Footer/index.module.scss, src/components/Header/index.module.scss, src/pages/home/SlideFooter/index.module.scss
fix: solve the compatibility problem of small font size
=> fix: solve the compatibility problem of small font size

src/components/BaseSeparatePage/index.module.scss, src/components/Footer/components/FooterLinkGroup/index.module.scss, src/components/Footer/index.module.scss, src/components/Footer/index.tsx, src/components/Page/index.module.scss, src/components/Pagination/index.module.scss, src/styles/presets.module.scss
=> feat: imrpove styles

next.config.mjs, src/components/BaseSeparatePage/Description/index.module.scss, src/components/BaseSeparatePage/Functions/index.module.scss, src/components/BaseSeparatePage/FunctionsItem/index.module.scss, src/components/BaseSeparatePage/Info/index.module.scss, src/components/BaseSeparatePage/Info/index.tsx, src/components/BaseSeparatePage/ProgressBar/index.module.scss, src/components/BaseSeparatePage/ProgressBar/index.tsx, src/components/BaseSeparatePage/Resources/index.module.scss, src/components/BaseSeparatePage/ResourcesItem/index.module.scss, src/components/BaseSeparatePage/ResourcesItem/index.tsx, src/components/BaseSeparatePage/Supports/index.tsx, src/components/BaseSeparatePage/index.module.scss, src/components/BaseSeparatePage/index.tsx, src/components/Header/index.module.scss, src/components/StyledLink/index.module.scss, src/components/StyledLink/index.tsx, src/pages/blogs/index.module.scss, src/pages/blogs/index.page.tsx, src/pages/ckbpage/index.page.tsx, src/pages/community/index.page.tsx, src/pages/developers/index.page.tsx, src/pages/foundation/index.page.tsx, src/pages/learn/index.page.tsx, src/pages/mining/index.page.tsx, src/pages/wallets/index.page.tsx
Adapts to the performance of each page at 750 ~ 1200 widths, and limit content max-width to 1200.
=> feat: adapts to the performance of each page at 750 ~ 1200 widths

src/components/BaseSeparatePage/FunctionsItem/index.module.scss, src/components/BaseSeparatePage/Supports/index.module.scss, src/components/BaseSeparatePage/index.module.scss, src/components/Footer/components/FooterMedia/SubscribeWrap.tsx, src/components/Footer/components/FooterMedia/index.module.scss, src/components/Footer/components/FooterMedia/index.tsx, src/components/Footer/index.module.scss, src/pages/foundation/index.module.scss
What problem does this PR solve?
------
As title.
Ref: https://github.com/Magickbase/nervos-official-website/issues/42
Check List
------
e2e Test
none
=> feat:complete subscribe feature and some other optimizings

src/components/StyledLink/index.tsx, src/pages/community/index.page.tsx, src/pages/wallets/index.page.tsx
1. remove link to meetups which is out of date
2. update tutorials of ckbull
3. open external links in new tab
=> feat: update links

src/pages/home/index.module.scss, src/pages/home/index.page.tsx
Before
https://user-images.githubusercontent.com/7271329/226859357-de4abd58-0c0f-40d9-8e53-9c6b52092bc8.mov
After
https://user-images.githubusercontent.com/7271329/226859426-fbb4a5e7-fc62-4e97-8aba-a0d180599cc7.mov
=> feat: optimzie layout of homepage for height < 780px

src/pages/home/index.page.tsx
Before
https://user-images.githubusercontent.com/7271329/227099672-cb0dfad3-3d61-43c1-a554-a20f65f17683.mov
After
https://user-images.githubusercontent.com/7271329/227099705-03ac78bc-646c-423c-b581-447c65f69bd6.mov
=> fix: patch scroll of homepage on mobile

src/pages/home/index.page.tsx
feat: make the scrolling trigger on the home page less sensitive
=> feat: make the scrolling trigger on the home page less sensitive

src/pages/home/index.module.scss, src/pages/home/index.page.tsx
feat: adapets to 375 width screens
Ref: https://nervos-official-website-git-update-content-an-913909-magickbase.vercel.app/developers#thread-id=jWwpd
=> feat: adapets to 375 width screens

src/pages/home/index.page.tsx
feat: complete the links on the homepage
Ref: #103
=> feat: complete the links on the homepage

src/pages/home/index.page.tsx, src/pages/knowledge-base/knowledgeBase.module.scss
=> Release 2023/04/13

next-i18next.config.js, src/components/Header/index.tsx, src/pages/knowledge-base/[slug].page.tsx, src/pages/knowledge-base/index.page.tsx, src/utils/blogs.ts
feat: Implement i18n support for edu articles
=> feat: Implement i18n support for edu articles

public/locales/es/common.json
=> Correct Spanish typo in common.json

src/components/OpenGraph/index.tsx, src/components/Page/index.tsx, src/pages/_app.page.tsx, src/pages/knowledge-base/[slug].page.tsx, src/pages/knowledge-base/index.page.tsx, src/utils/blogs.ts, src/utils/index.ts
=> Edu hub article link preview should show article info

src/utils/blogs.ts
=> fix(knowledge-base): tags showing more than once

src/pages/home/index.module.scss, src/pages/home/index.page.tsx
Reverts Magickbase/nervos-official-website#242
More discussions are required before this update onto the production
Ref: https://github.com/Magickbase/nervos-official-website/issues/251
=> Revert "chore: add CKB badge in banner text"

src/components/BaseSeparatePage/ContributorsDialog/index.tsx, src/components/BaseSeparatePage/FunctionsItem/index.tsx, src/components/Header/index.module.scss
Ref: https://github.com/Magickbase/nervos-official-website/pull/250#discussion_r1264806232
=> style: format by prettier@v3

.env.example, src/utils/blogs.ts, src/utils/env.ts
Try to resolve PR #211 not working in production environment
=> feat: support NEXT_BASE_URL env

public/locales/en/common.json, public/locales/es/common.json, public/locales/fr/common.json, public/locales/pt/common.json, public/locales/zh/common.json, src/components/Footer/index.tsx
1. rename 'press kit' as 'media kit'
2. update link of media kit
Ref: https://github.com/Magickbase/nervos-official-website/issues/269
=> feat: update media kit

src/pages/knowledge-base/[slug].page.tsx
Resolve: https://github.com/Magickbase/nervos-official-website/issues/296
preview：
=> fix: subtitle hyper links don't render

src/pages/knowledge-base/index.page.tsx
This PR patches issue https://github.com/Magickbase/nervos-official-website/issues/297
It sets image's URL to the raw image on GitHub if it's not hosted on Vercel.
=> fix: point thumbnail of article to raw images on github

public/locales/en/roadmap.json, public/locales/es/roadmap.json, public/locales/fr/roadmap.json, public/locales/ko/roadmap.json, public/locales/pt/roadmap.json, public/locales/tr/roadmap.json, public/locales/zh/roadmap.json
Ref: https://github.com/Magickbase/nervos-official-website/issues/175#issuecomment-1693902273
=> feat: update contents of roadmap page

public/locales/en/common.json, public/locales/es/common.json, public/locales/fr/common.json, public/locales/pt/common.json, public/locales/zh/common.json, src/components/Footer/index.tsx, src/components/Header/index.module.scss, src/components/Header/index.tsx
Preview:
Ref: https://github.com/Magickbase/nervos-official-website/issues/355
=> feat: add link of ckb node probe in navigation

.yarn/plugins/@yarnpkg/plugin-after-install.cjs, .yarnrc.yml, package.json
fix: the husky install command does not execute after the yarn install command
=> fix: the husky install command does not execute after the yarn install command

src/pages/wallets/index.page.tsx
Ref: https://github.com/Magickbase/nervos-official-website/issues/237
=> feat: use neuron project page instead of github as distribution platform

.eslintrc.cjs, public/scripts/google-analytics.js, public/scripts/twitter.js, src/pages/_app.page.tsx, src/utils/env.ts, src/utils/index.ts
1. add twitter tracker
2. add google analytics tracker
=> feat: add trackers

public/locales/en/developers.json, public/locales/es/developers.json, public/locales/fr/developers.json, public/locales/pt/developers.json, src/pages/developers/index.page.tsx
Refs: https://github.com/Magickbase/nervos-official-website/issues/385
=> Remove "Build Club" from "Developers Page"

public/locales/en/common.json, public/locales/es/common.json, public/locales/fr/common.json, public/locales/pt/common.json, public/locales/zh/common.json, src/components/Header/index.tsx
Ref: https://github.com/Magickbase/nervos-official-website/issues/410
=> feat: add ecosystem item in navigation

public/locales/en/home.json, public/locales/es/home.json, public/locales/fr/home.json, public/locales/pt/home.json, public/locales/zh/home.json, src/components/ConwayGameOfLife/index.tsx, src/components/ConwayGameOfLife/useGameKeybindings.ts, src/pages/home/SlideFooter/index.tsx, src/pages/home/index.module.scss, src/pages/home/index.page.tsx
Refs: https://github.com/Magickbase/nervos-official-website/issues/430
=> Improve interactive

src/components/Footer/components/FooterLinkGroup/index.tsx
Kepp click event propagating to link elements
Ref: https://github.com/Magickbase/nervos-official-website/issues/446
=> fix: fix click event of link in footer

.env.example, package.json, src/pages/knowledge-base/[slug].page.tsx, src/pages/knowledge-base/index.module.scss, src/pages/knowledge-base/index.page.tsx, src/pages/knowledge-base/knowledgeBase.module.scss, src/utils/blogs.ts, src/utils/gadata.ts, yarn.lock
reslove: https://github.com/Magickbase/nervos-official-website/issues/450
=> feat: add page view on article page

public/locales/en/common.json, public/locales/es/common.json, public/locales/fr/common.json, public/locales/pt/common.json, public/locales/zh/common.json
* remove duplicate ecosystem text which causes warning
=> docs: remove duplicate text
